sudo: false
language: node_js
node_js:
  - stable
  - 'iojs'
  - '0.12'
  - '0.10'
deploy:
  provider: npm
  email: pattyn.kurt@gmail.com
  api_key:
    secure: h0yMmTqEPtae0DSjr8gZAU4qi+Ek8iSfFNocgp3NChTv9UEt0m5ZP0KGE9wZ65gU/9HZOI4q1wI9y3KPk5Xuos/s8byQDcEi2oCqFOmzzsfrZRF5ErUbWCt8TvOFINT2nUUKaT8iUlizxEJr2uhMzlwdyXRUhAwhqTKCa4NtEodZqy/evxCgBaKqtdFVf25nez1YWFaqBTKP5PXQ/0x/y3kyfNp8Y4XSBenNATyZbfSc54jRVIGVkx1Srv5L30ZWqcfk+OlfS0x0KiiGPyf89cAeKFrmwATu+4DoEzDDQS2U5j18EIxuz1OG7KbCjOmmiBOSljzEwlkeIFGFZMS3wIHGidB73WO42e+itRbrSgJXe8AdUn2JK2hUBSF4zimq0HI3tIMaR9qP1dMOwCxDVcOWQivV+WNKZu63VGKzbNXsxZuFyd/HKDJrIeevDMDrS/dyJduEsd23qKQg6ycS6IeNqMN2UcnacI8XcYzVQ1sSX5LIGf7qLS0P+HC70+ufV/OR18eADihE5txd4Bnwla07OzdHLuyZ/tvKXE4q9ytToRcgQZZWCFHEQ9mG9X9zK/JIUF9pXTGE4zwYtwbSSESNmukvpzGaES8pDCCB2TjqeOF8ChFQFUB86DAyXo38UDY/UOkpMoTNqSLTvqnFLN22EZavuIWp5akU6XG/UYc=
  on:
    tags: true
    repo: KurtPattyn/generator-krew
    branch: master
