sudo: false
language: node_js
node_js:
  - stable
  - 'iojs'
  - '0.12'
  - '0.10'
deploy:
  provider: npm
  email: pattyn.kurt@gmail.com
  api_key:
    secure: BVThiQtNvR+VGcIPhHXrkWaPP0pIHJeTKV1HnAEohWKC2iQkh9OHTJCsEUpDNjDncLEc7N/UTIxHYTqDQEF7FHrqwSw5Cy8FDIn1CjhtuWGwkCK8nytHEYYCNF5oXRq0tSoVktp5tBDDMAFH0a3QSNuwcZLNvVYQlCAi2XaAdFvqdDpE1KiaHUJgV7kuirZ5R9iJqxu9Rygi4m2lkTARReV+q8e0iMwutlmbJReCzFc+hXZfjAK1HIdBtabRtSiENohMAj0RQzMTTXyB+UbpXhSTUiUO9VVtQfeVV6N6LY1Vb3lMXgyKOJWsnvcSzsLl6XRFfJtRcmOGu/hYja6X2uGUfqUF9fxfxOj6YtSYgGwa/2ngEGRPiTCeeBaGlpF0hu3KbhLWDwgxxN2WVVbbtmdGzOt2RIPeJUaFT8zFiFMUp33WUForoiRJL9vqUzMYiAaKaUetxeYJF5CzkfTLMKElAdhgbqgpc3IW1mkG4xvhh9AwNCnMsFzmSx2n3Ec/dgK8JWWhrUGtOhSGHhoqRl8JZdX81N0eXYn/AhJ3rSWpSC1ZJwapuXHN/nOXC3tyQHUE+iDVqrfHx6hLntGb6I09om7q3kME4r6ia04yiYSdLI+rc7i0pgphkN1+gOgPpDPCYdecpeK/pCS/2qPzousIy4KHkqZyQIcf9jgMVOc=
  on:
    tags: true
    repo: KurtPattyn/generator-krew
    branch: master
